import forms from "@tailwindcss/forms";
/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#e2dfff",
        secondary: "#006c49",
        "on-primary-fixed-variant": "#3323cc",
        "surface-variant": "#d3e4fe",
        "inverse-on-surface": "#eaf1ff",
        "on-secondary-container": "#00714d",
        "tertiary-container": "#a44100",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "surface-dim": "#cbdbf5",
        "secondary-fixed": "#6ffbbe",
        "primary-fixed-dim": "#c3c0ff",
        outline: "#777587",
        "tertiary-fixed": "#ffdbcc",
        "surface-container-highest": "#d3e4fe",
        "error-container": "#ffdad6",
        "secondary-container": "#6cf8bb",
        "on-tertiary-fixed": "#351000",
        "primary-container": "#4f46e5",
        primary: "#3525cd",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#0f0069",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#4edea3",
        "on-secondary-fixed": "#002113",
        "surface-container-low": "#eff4ff",
        "on-surface-variant": "#464555",
        "on-tertiary": "#ffffff",
        "on-background": "#0b1c30",
        "outline-variant": "#c7c4d8",
        tertiary: "#7e3000",
        "on-secondary-fixed-variant": "#005236",
        "surface-container-high": "#dce9ff",
        "inverse-surface": "#213145",
        "inverse-primary": "#c3c0ff",
        "surface-tint": "#4d44e3",
        "on-surface": "#0b1c30",
        error: "#ba1a1a",
        "surface-bright": "#f8f9ff",
        surface: "#f8f9ff",
        "surface-container": "#e5eeff",
        "tertiary-fixed-dim": "#ffb695",
        "on-tertiary-container": "#ffd2be",
        "on-primary-container": "#dad7ff",
        "on-tertiary-fixed-variant": "#7b2f00",
        "on-error-container": "#93000a",
        background: "#f8f9ff",
        emerald: "#10B981",
        // Dark-mode neutrals (per DESIGN.md elevation guidance)
        "dark-surface": "#0b1220",
        "dark-surface-container": "#111a2e",
        "dark-card": "#1e293b",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.25rem",
        lg: "0.5rem",
        xl: "12px",
        "2xl": "14px",
        input: "10px",
        card: "14px",
        full: "9999px",
      },
      spacing: {
        "container-max": "1280px",
        "margin-mobile": "16px",
        xs: "4px",
        sm: "8px",
        base: "4px",
        gutter: "24px",
        lg: "24px",
        xl: "40px",
        md: "16px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        "headline-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "headline-lg": ["Inter"],
        "body-md": ["Inter"],
        "body-sm": ["Inter"],
        "label-caps": ["Inter"],
        display: ["Inter"],
        "body-lg": ["Inter"],
        "tabular-time": ["Inter"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        display: ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "tabular-time": ["16px", { lineHeight: "1", fontWeight: "500" }],
      },
      boxShadow: {
        ambient: "0px 4px 20px rgba(0,0,0,0.05)",
      },
    },
  },
  plugins: [forms],
};
